/* eslint-disable no-console */
/**
 * Generates a static import-map file for Search cards using ES6 imports.
 *
 * React Native Metro works best with ES6 imports for assets,
 * so we generate a TypeScript file with static import statements.
 *
 * Usage:
 *   node scripts/generateSearchCardAssets.js
 */

const fs = require('fs');
const path = require('path');

const projectRoot = path.join(__dirname, '..');
const assetsRoot = path.join(projectRoot, 'assets');

const OUT_FILE = path.join(projectRoot, 'src', 'assets', 'searchCardAssets.generated.ts');

function listPngBaseNames(dirAbs) {
  if (!fs.existsSync(dirAbs)) return [];
  return fs
    .readdirSync(dirAbs, { withFileTypes: true })
    .filter((d) => d.isFile())
    .map((d) => d.name)
    .filter((name) => name.toLowerCase().endsWith('.png'))
    .map((name) => name.slice(0, -4))
    .sort((a, b) => a.localeCompare(b));
}

function toImportLines(names, relImportPrefix) {
  return names.map((n) => {
    const varName = n.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '_');
    return `import ${varName} from '${relImportPrefix}/${n}.png';`;
  });
}

function toObjectMapLines(names) {
  return names.map((n) => {
    const varName = n.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '_');
    return `  ${JSON.stringify(n)}: ${varName},`;
  });
}

function main() {
  const countries = listPngBaseNames(path.join(assetsRoot, 'countries'));
  const cities = listPngBaseNames(path.join(assetsRoot, 'cities'));
  const regions = listPngBaseNames(path.join(assetsRoot, 'region'));

  const lines = [];
  lines.push('/* AUTO-GENERATED FILE. DO NOT EDIT. */');
  lines.push('/* Generated by scripts/generateSearchCardAssets.js */');
  lines.push('');
  
  // Import statements
  lines.push('// Country imports');
  lines.push(...toImportLines(countries, '../../assets/countries'));
  lines.push('');
  lines.push('// Region imports');
  lines.push(...toImportLines(regions, '../../assets/region'));
  lines.push('');
  lines.push('// City imports');
  lines.push(...toImportLines(cities, '../../assets/cities'));
  lines.push('');
  
  // Export objects
  lines.push('export const COUNTRY_CARD_IMAGES: Record<string, any> = {');
  lines.push(...toObjectMapLines(countries));
  lines.push('};');
  lines.push('');
  lines.push('export const REGION_CARD_IMAGES: Record<string, any> = {');
  lines.push(...toObjectMapLines(regions));
  lines.push('};');
  lines.push('');
  lines.push('export const CITY_CARD_IMAGES: Record<string, any> = {');
  lines.push(...toObjectMapLines(cities));
  lines.push('};');
  lines.push('');
  lines.push("export const DEFAULT_CARD_IMAGE = REGION_CARD_IMAGES['Europe'] || Object.values(REGION_CARD_IMAGES)[0];");
  lines.push('');

  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');

  console.log(`[gen:cards] Wrote ${path.relative(projectRoot, OUT_FILE)}`);
  console.log(`[gen:cards] countries=${countries.length} regions=${regions.length} cities=${cities.length}`);
}

main();

