/* eslint-disable no-console */
/**
 * Generates a static require-map file for Search cards.
 *
 * React Native Metro cannot "auto-require" images dynamically from the filesystem at runtime,
 * so we generate a TypeScript file with static require() calls.
 *
 * Usage:
 *   node scripts/generateSearchCardAssets.js
 */

const fs = require('fs');
const path = require('path');

const projectRoot = path.join(__dirname, '..');
const assetsRoot = path.join(projectRoot, 'assets');

const OUT_FILE = path.join(projectRoot, 'src', 'assets', 'searchCardAssets.generated.ts');

function listPngBaseNames(dirAbs) {
  if (!fs.existsSync(dirAbs)) return [];
  return fs
    .readdirSync(dirAbs, { withFileTypes: true })
    .filter((d) => d.isFile())
    .map((d) => d.name)
    .filter((name) => name.toLowerCase().endsWith('.png'))
    .map((name) => name.slice(0, -4))
    .sort((a, b) => a.localeCompare(b));
}

function toObjectMapLines(names, relRequirePrefix) {
  return names.map((n) => `  ${JSON.stringify(n)}: require('${relRequirePrefix}/${n}.png'),`);
}

function main() {
  const countries = listPngBaseNames(path.join(assetsRoot, 'countries'));
  const cities = listPngBaseNames(path.join(assetsRoot, 'cities'));
  const regions = listPngBaseNames(path.join(assetsRoot, 'region'));

  const lines = [];
  lines.push('/* AUTO-GENERATED FILE. DO NOT EDIT. */');
  lines.push('/* Generated by scripts/generateSearchCardAssets.js */');
  lines.push('');
  lines.push('export const COUNTRY_CARD_IMAGES: Record<string, any> = {');
  lines.push(...toObjectMapLines(countries, '../../assets/countries'));
  lines.push('};');
  lines.push('');
  lines.push('export const REGION_CARD_IMAGES: Record<string, any> = {');
  lines.push(...toObjectMapLines(regions, '../../assets/region'));
  lines.push('};');
  lines.push('');
  lines.push('export const CITY_CARD_IMAGES: Record<string, any> = {');
  lines.push(...toObjectMapLines(cities, '../../assets/cities'));
  lines.push('};');
  lines.push('');
  lines.push("export const DEFAULT_CARD_IMAGE = REGION_CARD_IMAGES['Europe'] || Object.values(REGION_CARD_IMAGES)[0];");
  lines.push('');

  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');

  console.log(`[gen:cards] Wrote ${path.relative(projectRoot, OUT_FILE)}`);
  console.log(`[gen:cards] countries=${countries.length} regions=${regions.length} cities=${cities.length}`);
}

main();

