/* AUTO-GENERATED FILE. DO NOT EDIT. */
/* Generated by scripts/generateSearchCardAssets.js */

// Country imports
import Canada from '../../assets/countries/Canada.png';
import China from '../../assets/countries/China.png';
import France from '../../assets/countries/France.png';
import Greece from '../../assets/countries/Greece.png';
import Italy from '../../assets/countries/Italy.png';
import Mexico from '../../assets/countries/Mexico.png';
import Portugal from '../../assets/countries/Portugal.png';
import Saudi_Arabia from '../../assets/countries/Saudi Arabia.png';
import Spain from '../../assets/countries/Spain.png';
import Switzerland from '../../assets/countries/Switzerland.png';
import Thailand from '../../assets/countries/Thailand.png';
import Turkey from '../../assets/countries/Turkey.png';
import United_Arab_Emirates from '../../assets/countries/United Arab Emirates.png';
import United_Kingdom from '../../assets/countries/United Kingdom.png';
import United_States from '../../assets/countries/United States.png';

// Region imports
import Africa from '../../assets/region/Africa.png';
import Asia from '../../assets/region/Asia.png';
import Caribbean from '../../assets/region/Caribbean.png';
import East_Asia from '../../assets/region/East Asia.png';
import Europe from '../../assets/region/Europe.png';
import North_America from '../../assets/region/North America.png';
import Oceania from '../../assets/region/Oceania.png';
import South_America from '../../assets/region/South America.png';
import Southeast_Asia from '../../assets/region/Southeast Asia.png';

// City imports
import Amsterdam from '../../assets/cities/Amsterdam.png';
import Bangkok from '../../assets/cities/Bangkok.png';
import Barcelona from '../../assets/cities/Barcelona.png';
import Dubai from '../../assets/cities/Dubai.png';
import Hong_Kong from '../../assets/cities/Hong Kong.png';
import Istanbul from '../../assets/cities/Istanbul.png';
import Las_Vegas from '../../assets/cities/Las Vegas.png';
import London from '../../assets/cities/London.png';
import Los_Angeles from '../../assets/cities/Los Angeles.png';
import New_York_City from '../../assets/cities/New York City.png';
import Paris from '../../assets/cities/Paris.png';
import Rome from '../../assets/cities/Rome.png';
import Seoul from '../../assets/cities/Seoul.png';
import Singapore from '../../assets/cities/Singapore.png';
import Sydney from '../../assets/cities/Sydney.png';
import Tokyo from '../../assets/cities/Tokyo.png';

export const COUNTRY_CARD_IMAGES: Record<string, any> = {
  "Canada": Canada,
  "China": China,
  "France": France,
  "Greece": Greece,
  "Italy": Italy,
  "Mexico": Mexico,
  "Portugal": Portugal,
  "Saudi Arabia": Saudi_Arabia,
  "Spain": Spain,
  "Switzerland": Switzerland,
  "Thailand": Thailand,
  "Turkey": Turkey,
  "United Arab Emirates": United_Arab_Emirates,
  "United Kingdom": United_Kingdom,
  "United States": United_States,
};

export const REGION_CARD_IMAGES: Record<string, any> = {
  "Africa": Africa,
  "Asia": Asia,
  "Caribbean": Caribbean,
  "East Asia": East_Asia,
  "Europe": Europe,
  "North America": North_America,
  "Oceania": Oceania,
  "South America": South_America,
  "Southeast Asia": Southeast_Asia,
};

export const CITY_CARD_IMAGES: Record<string, any> = {
  "Amsterdam": Amsterdam,
  "Bangkok": Bangkok,
  "Barcelona": Barcelona,
  "Dubai": Dubai,
  "Hong Kong": Hong_Kong,
  "Istanbul": Istanbul,
  "Las Vegas": Las_Vegas,
  "London": London,
  "Los Angeles": Los_Angeles,
  "New York City": New_York_City,
  "Paris": Paris,
  "Rome": Rome,
  "Seoul": Seoul,
  "Singapore": Singapore,
  "Sydney": Sydney,
  "Tokyo": Tokyo,
};

export const DEFAULT_CARD_IMAGE = REGION_CARD_IMAGES['Europe'] || Object.values(REGION_CARD_IMAGES)[0];
