/* AUTO-GENERATED FILE. DO NOT EDIT. */
/* Generated by scripts/generateSearchCardAssets.js */

export const COUNTRY_CARD_IMAGES: Record<string, any> = {
  "Canada": require('../assets/countries/Canada.png'),
  "China": require('../assets/countries/China.png'),
  "France": require('../assets/countries/France.png'),
  "Greece": require('../assets/countries/Greece.png'),
  "Italy": require('../assets/countries/Italy.png'),
  "Mexico": require('../assets/countries/Mexico.png'),
  "Portugal": require('../assets/countries/Portugal.png'),
  "Saudi Arabia": require('../assets/countries/Saudi Arabia.png'),
  "Spain": require('../assets/countries/Spain.png'),
  "Switzerland": require('../assets/countries/Switzerland.png'),
  "Thailand": require('../assets/countries/Thailand.png'),
  "Turkey": require('../assets/countries/Turkey.png'),
  "United Arab Emirates": require('../assets/countries/United Arab Emirates.png'),
  "United Kingdom": require('../assets/countries/United Kingdom.png'),
  "United States": require('../assets/countries/United States.png'),
};

export const REGION_CARD_IMAGES: Record<string, any> = {
  "Africa": require('../assets/region/Africa.png'),
  "Asia": require('../assets/region/Asia.png'),
  "Caribbean": require('../assets/region/Caribbean.png'),
  "East Asia": require('../assets/region/East Asia.png'),
  "Europe": require('../assets/region/Europe.png'),
  "North America": require('../assets/region/North America.png'),
  "Oceania": require('../assets/region/Oceania.png'),
  "South America": require('../assets/region/South America.png'),
  "Southeast Asia": require('../assets/region/Southeast Asia.png'),
};

export const CITY_CARD_IMAGES: Record<string, any> = {
  "Amsterdam": require('../assets/cities/Amsterdam.png'),
  "Bangkok": require('../assets/cities/Bangkok.png'),
  "Barcelona": require('../assets/cities/Barcelona.png'),
  "Dubai": require('../assets/cities/Dubai.png'),
  "Hong Kong": require('../assets/cities/Hong Kong.png'),
  "Istanbul": require('../assets/cities/Istanbul.png'),
  "Las Vegas": require('../assets/cities/Las Vegas.png'),
  "London": require('../assets/cities/London.png'),
  "Los Angeles": require('../assets/cities/Los Angeles.png'),
  "New York City": require('../assets/cities/New York City.png'),
  "Paris": require('../assets/cities/Paris.png'),
  "Rome": require('../assets/cities/Rome.png'),
  "Seoul": require('../assets/cities/Seoul.png'),
  "Singapore": require('../assets/cities/Singapore.png'),
  "Sydney": require('../assets/cities/Sydney.png'),
  "Tokyo": require('../assets/cities/Tokyo.png'),
};

export const DEFAULT_CARD_IMAGE = REGION_CARD_IMAGES['Europe'] || Object.values(REGION_CARD_IMAGES)[0];
