import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: '#fff',
    gap: 10,
  },
  cardHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 22.5,
    backgroundColor: '#eee',
    borderWidth: 1.5,
    borderColor: '#e0e0e0',
    overflow: 'hidden',
  },
  cardHeaderInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  cardHeaderName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#111',
    lineHeight: 17,
    marginBottom: 0,
  },
  cardHeaderSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
  },
  cardHeaderLocation: {
    fontSize: 14,
    color: '#222',
    fontWeight: '400',
  },
  cardHeaderDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#aaa',
    marginHorizontal: 5,
  },
  cardHeaderDate: {
    fontSize: 14,
    color: '#222',
    fontWeight: '400',
  },
  imageWrap: {
    width: '100%',
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: 'center',
    marginTop: 0,
  },
  image: {
    width: '100%',
    height: '100%',
    alignSelf: 'center',
  },
  iconRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'space-between',
    paddingHorizontal: 11,
    paddingTop: 9,
    paddingBottom: 0,
  },
  iconRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  iconRowRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    gap: 4,
  },
  iconRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 3,
  },
  captionWrap: {
    paddingHorizontal: 11,
    paddingTop: 2,
    paddingBottom: 0,
  },
  caption: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    letterSpacing: 0.14,
    textAlign: 'left',
    color: '#111',
  },
  hashtags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 6,
  },
  hashtag: {
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  hashtagText: {
    color: '#667eea',
    fontSize: 12,
    fontWeight: '600',
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    minHeight: 24,
  },
  actionCount: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111',
  },
  cardInner: {
    backgroundColor: '#fff',
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 0,
    paddingTop: 10,
    paddingBottom: 4,
    overflow: 'hidden',
  },
  reactionEmoji: {
    fontSize: 16,
  },
  reactionCount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
  },
  muteButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  videoControlsBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(0,0,0,0.4)',
    zIndex: 10,
  },
  videoProgressBar: {
    flex: 1,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 2,
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  videoProgressFill: {
    height: '100%',
    backgroundColor: '#fff',
    borderRadius: 2,
  },
  videoTimeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '500',
    minWidth: 35,
  },
});
